# site description
description = "Manan's Personal Blog"
# site keywords
keywords = ["Blog", "OpenSource", "Coding", "Programming", "Deep Learning", "Machine Learning", "AI", "Computer Vision"]
# App icon config
[app]
  # optional site title override for the app when added to an iOS home screen or Android launcher
  title = "Manan's Blog"
  # whether to omit favicon resource links
  noFavicon = false
  # modern SVG favicon to use in place of older style .png and .ico files
  svgFavicon = ""
  # Safari mask icon color
  iconColor = "#5bbad5"
  # Windows v8-10 tile color
  tileColor = "#da532c"
# Search config
[search]
  enable = true
  # type of search engine ("algolia", "fuse")
  type = "fuse"
  # max index length of the chunked content
  contentLength = 4000
  # placeholder of the search bar
  placeholder = ""
  # max number of results length
  maxResultLength = 10
  # snippet length of the result
  snippetLength = 300
  # HTML tag name of the highlight part in results
  highlightTag = "em"
  # whether to use the absolute URL based on the baseURL in search index
  absoluteURL = false
  [search.algolia]
    index = ""
    appID = ""
    searchKey = ""
  [search.fuse]
    # https://fusejs.io/api/options.html
    isCaseSensitive = false
    minMatchCharLength = 2
    findAllMatches = false
    location = 0
    threshold = 0.1
    distance = 100
    ignoreLocation = true
    useExtendedSearch = false
    ignoreFieldNorm = false
# Home page config
[home]
  # amount of RSS pages
  rss = 10
  # Home page profile
  [home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = ""
    # URL of avatar shown in home page
    avatarURL = "https://avatars.githubusercontent.com/cs-mshah"
    # URL the avatar links to
    avatarLinkURL = ""
    # title shown in home page (HTML format is supported)
    title = "Manan's Blog"
    # subtitle shown in home page
    subtitle = "My personal blog where I share my technical musings!"
    # whether to use typeit animation for subtitle
    typeit = true
    # whether to show social links
    social = true
    # disclaimer (HTML format is supported)
    disclaimer = ""
  # Home page posts
  [home.posts]
    enable = true
    # special amount of posts in each home posts page
    paginate = 5
# Social config in home page
[social]
  Angellist = ""
  Bandcamp = ""
  Behance = ""
  Bilibili = ""
  Bitbucket = ""
  BuyMeACoffee = ""
  Codepen = ""
  Deviantart = ""
  Devto = ""
  Douban = ""
  Dribbble = ""
  Email = "mt-shah@hotmail.com"
  Facebook = ""
  Fivehundredpx = ""
  Flickr = ""
  Foursquare = ""
  FreeCodeCamp = ""
  Gitea = ""
  GitHub = "cs-mshah"
  Gitlab = ""
  Goodreads = ""
  Googlescholar = "iIIm36YAAAAJ"
  Hackernews = ""
  Instagram = ""
  Jsfiddle = ""
  Keybase = ""
  Kickstarter = ""
  Ko-Fi = ""
  Lastfm = ""
  Liberapay = ""
  Linkedin = "manan-shah-2a5779212"
  Linktree = ""
  Matrix = ""
  Medium = ""
  Mix = ""
  Odnoklassniki = ""
  ORCID = ""
  Patreon = ""
  Paypal = ""
  Pinterest = ""
  QQ = ""
  QQGroup = ""
  Quora = ""
  Reddit = ""
  Researchgate = ""
  RSS = true
  Skype = ""
  Slidershare = ""
  Snapchat = ""
  Soundcloud = ""
  Spotify = ""
  Stackoverflow = "13697903"
  Steam = ""
  Strava = ""
  Telegram = ""
  Thingiverse = ""
  Tumblr = ""
  Twitch = ""
  Twitter = "cs_mshah"
  Vine = ""
  VK = ""
  Weibo = ""
  Whatsapp = ""
  Wordpress = ""
  Xing = ""
  XMPP = ""
  Youtubechannel = ""
  Youtubecustom = ""
  Youtubelegacy = ""
  Zhihu = ""
  # [social.Mastodon]
  #   id = "@xxxx"
  #   prefix = "https://mastodon.technology/"
  # [social.Diaspora]
  #   id = "@xxxx"
  #   prefix = "https://yyyy/"
# Sponsor config
[sponsor]
  enable = false
  bio = "If you find this post helpful, please consider sponsoring."
  link = "https://github.com/sponsors/HEIGE-PCloud"
  # custom = "<a href=\"https://www.buymeacoffee.com/PCloud\" target=\"_blank\"><img src=\"https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png\" alt=\"Buy Me A Coffee\" style=\"height: 40px !important;width: 145 !important;\" ></a>"
