title: "Manan's Blog"
author:
  name: 'Manan Shah'
  email: 'mt-shah@hotmail.com'
  link: ''
menu:
  main:
    - weight: 1
      identifier: posts
      pre: ''
      post: ''
      name: Posts
      url: /posts/
      title: ''
    - weight: 2
      identifier: tags
      pre: ''
      post: ''
      name: Tags
      url: /tags/
      title: ''
    - weight: 3
      identifier: categories
      pre: ''
      post: ''
      name: Categories
      url: /categories/
      title: ''
markup:
  highlight:
    noClasses: false
